In [1]:
import numpy as np
from datascience import *
import matplotlib
matplotlib.use('Agg', warn=False)
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use ('fivethirtyeight')

In [2]:
number_flips = 10            # number of flips in each experiment
sample_size = 100             # number of experiments to run for each simulation
number_of_simulation = 1000

def run_experiment(number_flips):
    coinOutcomes = make_array('H', 'T')
    streak = np.random.choice(coinOutcomes, number_flips)
    t = 1
    flag = 0
    for i in range(len(streak) - 1):
        if streak[i + 1] == streak[i]:
            t += 1
        else:
            if t > flag:
                flag = t
            t = 1
    return flag

def collect_sample(sample_size, number_flips):
    numstreak = np.empty(sample_size)
    for i in range(sample_size):
        numstreak[i] = run_experiment(number_flips)
    return numstreak

def run_simulation_correct(number_of_simulation, sample_size, number_flips):
    variance_statistic = np.empty(number_of_simulation)
    for i in range(number_of_simulation):
        variance_statistic[i] = np.mean(collect_sample(sample_size, number_flips))
    return variance_statistic

In [3]:
np.mean(run_simulation_correct(number_of_simulation, sample_size, number_flips))

3.3126400000000005

when flipping 10 coins, the simulation value is 3.3126

In [4]:
number_flips = 100            # number of flips in each experiment
sample_size = 100             # number of experiments to run for each simulation
number_of_simulation = 1000

def run_experiment(number_flips):
    coinOutcomes = make_array('H', 'T')
    streak = np.random.choice(coinOutcomes, number_flips)
    t = 1
    flag = 0
    for i in range(len(streak) - 1):
        if streak[i + 1] == streak[i]:
            t += 1
        else:
            if t > flag:
                flag = t
            t = 1
    return flag

def collect_sample(sample_size, number_flips):
    numstreak = np.empty(sample_size)
    for i in range(sample_size):
        numstreak[i] = run_experiment(number_flips)
    return numstreak

def run_simulation_correct(number_of_simulation, sample_size, number_flips):
    variance_statistic = np.empty(number_of_simulation)
    for i in range(number_of_simulation):
        variance_statistic[i] = np.mean(collect_sample(sample_size, number_flips))
    return variance_statistic

In [5]:
np.mean(run_simulation_correct(number_of_simulation, sample_size, number_flips))

6.9444099999999995

when flipping 100 coins, the simulation value is 6.9444

In [6]:
number_flips = 1000           # number of flips in each experiment
sample_size = 100             # number of experiments to run for each simulation
number_of_simulation = 1000

def run_experiment(number_flips):
    coinOutcomes = make_array('H', 'T')
    streak = np.random.choice(coinOutcomes, number_flips)
    t = 1
    flag = 0
    for i in range(len(streak) - 1):
        if streak[i + 1] == streak[i]:
            t += 1
        else:
            if t > flag:
                flag = t
            t = 1
    return flag

def collect_sample(sample_size, number_flips):
    numstreak = np.empty(sample_size)
    for i in range(sample_size):
        numstreak[i] = run_experiment(number_flips)
    return numstreak

def run_simulation_correct(number_of_simulation, sample_size, number_flips):
    variance_statistic = np.empty(number_of_simulation)
    for i in range(number_of_simulation):
        variance_statistic[i] = np.mean(collect_sample(sample_size, number_flips))
    return variance_statistic

In [7]:
np.mean(run_simulation_correct(number_of_simulation, sample_size, number_flips))

10.28741

when flipping 1000 coins, the simulation value is 10.28741

In [8]:
number_flips = 10000            # number of flips in each experiment
sample_size = 10             # number of experiments to run for each simulation
number_of_simulation = 1000

def run_experiment(number_flips):
    coinOutcomes = make_array('H', 'T')
    streak = np.random.choice(coinOutcomes, number_flips)
    t = 1
    flag = 0
    for i in range(len(streak) - 1):
        if streak[i + 1] == streak[i]:
            t += 1
        else:
            if t > flag:
                flag = t
            t = 1
    return flag

def collect_sample(sample_size, number_flips):
    numstreak = np.empty(sample_size)
    for i in range(sample_size):
        numstreak[i] = run_experiment(number_flips)
    return numstreak

def run_simulation_correct(number_of_simulation, sample_size, number_flips):
    variance_statistic = np.empty(number_of_simulation)
    for i in range(number_of_simulation):
        variance_statistic[i] = np.mean(collect_sample(sample_size, number_flips))
    return variance_statistic

In [9]:
np.mean(run_simulation_correct(number_of_simulation, sample_size, number_flips))

13.6147

when flipping 10000 coins, the simulation value is 13.6147

In [14]:
number_flips = 100000            # number of flips in each experiment
sample_size = 5             # number of experiments to run for each simulation
number_of_simulation = 100

def run_experiment(number_flips):
    coinOutcomes = make_array('H', 'T')
    streak = np.random.choice(coinOutcomes, number_flips)
    t = 1
    flag = 0
    for i in range(len(streak) - 1):
        if streak[i + 1] == streak[i]:
            t += 1
        else:
            if t > flag:
                flag = t
            t = 1
    return flag

def collect_sample(sample_size, number_flips):
    numstreak = np.empty(sample_size)
    for i in range(sample_size):
        numstreak[i] = run_experiment(number_flips)
    return numstreak

def run_simulation_correct(number_of_simulation, sample_size, number_flips):
    variance_statistic = np.empty(number_of_simulation)
    for i in range(number_of_simulation):
        variance_statistic[i] = np.mean(collect_sample(sample_size, number_flips))
    return variance_statistic

In [15]:
np.mean(run_simulation_correct(number_of_simulation, sample_size, number_flips))

17.020000000000003

when flipping 100000 coins, the simulation value is 17.02